version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:50001
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    volumes:
      - ../storage:/app/storage
    restart: always